name: build-and-push
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push WEB image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.node
          push: true
          tags: |
            ghcr.io/gergananoneva/astromatchapp-web:latest
            ghcr.io/gergananoneva/astromatchapp-web:${{ github.sha }}
          platforms: linux/amd64

      - name: Build & push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.python
          push: true
          tags: |
            ghcr.io/gergananoneva/astromatchapp-api:latest
            ghcr.io/gergananoneva/astromatchapp-api:${{ github.sha }}
          platforms: linux/amd64
